
<nav class="navbar">
  <div class="container">
    <div class="row">
    
        <div class="col-md">
            <div class="row">
                <img src="images/bg_3basy.jpeg" class="logo">
                <h2 class="logo-text">3BASY STORE</h2>
            </div>
        </div>


        <div class="col-md">
            <form class="form-inline search-form">
                <input type="text" placeholder="Search" class="form-control"/>
                <button type="submit" class="btn btn-success">search</button>
            </form>
        </div>  
    </div>
</nav>
